
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
remappings = ["forge-std/=lib/forge-std/src/"]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
localhost = "http://localhost:8545"
